/**
 * Entrypoint shell script generator.
 *
 * Docker bind mounts that don't exist on the host get auto-created by
 * docker-compose at `up` time — but as root-owned directories.  Our agents
 * run as the `bun` user (UID 1000) inside the container, so they can't
 * write to those root-owned dirs and crash on first state-write.
 *
 * Solution: ENTRYPOINT runs as root, chowns every RW bind-mount target,
 * then exec-drops to `bun` via gosu.  The container's CMD becomes the
 * `bun src/index.ts ...` invocation, executed under bun's UID.
 *
 * The list of paths to chown comes from compose.ts's `chownTargets`
 * helper so the two generators stay in lockstep — anything compose
 * mounts RW gets chown'd here.
 *
 * Runtime-rendered templates: when a recipe's `containerTemplateFiles`
 * entry declares `runtimeRender: true`, cook bind-mounts the template at
 * `<inContainer>.tmpl` instead of `<inContainer>`.  The entrypoint here
 * pulls bot/admin/secret values from a shared bootstrap volume at
 * `/bootstrap/state/`, exports them, and envsubsts each `.tmpl` into its
 * final destination inside the container's writable layer.  Order:
 * envsubst FIRST, then chown, then drop to bun.
 */

import type { GeneratorInput } from '../types.js';
import { chownTargets } from './compose.js';

export function generateEntrypoint(input: GeneratorInput): string {
  const targets = chownTargets(input.walks);
  const chownLine = targets.length > 0
    ? `chown -R bun:bun ${targets.join(' ')}`
    : '# no RW bind-mount targets to chown';

  const parent = input.walks[0]!;
  const runtimeTemplates = (parent.recipe.containerTemplateFiles ?? [])
    .filter((tf) => tf.runtimeRender === true || (tf.runtimeVars?.length ?? 0) > 0);

  const lines: string[] = [
    '#!/bin/sh',
    '#',
    '# Auto-generated by connectome-cook.  Runs as root at container start,',
    '# fixes ownership of bind-mounted dirs (which docker-compose creates as',
    '# root if the host paths did not exist), then exec-drops to the `bun`',
    '# user via gosu and runs the CMD (`bun src/index.ts <recipe>` by default).',
    '#',
    '# This is the standard Postgres/Redis-style "container init as root,',
    '# real work as service user" pattern — needed because RW bind mounts',
    '# punch through the in-image chown.',
    '#',
    'set -e',
    '',
  ];

  if (runtimeTemplates.length > 0) {
    lines.push(
      '# Runtime-rendered config files.  Cook bind-mounts these as <path>.tmpl',
      '# (read-only); we envsubst them into <path> in the container writable',
      '# layer.  Values come from /bootstrap/state/ (written by a bootstrap',
      '# sidecar that runs to completion before this container starts) and',
      '# from the env-file vars compose already exported.',
      'if [ -d /bootstrap/state ]; then',
      '  # Read each state file into a matching env var.  File names are the',
      '  # env-var names lowercased (kebab is converted by the bootstrap; we',
      '  # only convention bot-password -> WIKI_BOT_PASSWORD for now).',
      '  if [ -f /bootstrap/state/bot-password ]; then',
      '    WIKI_BOT_PASSWORD=$(cat /bootstrap/state/bot-password)',
      '    export WIKI_BOT_PASSWORD',
      '  fi',
      'fi',
      '',
    );
    for (const tf of runtimeTemplates) {
      const dst = tf.inContainer;
      const src = `${tf.inContainer}.tmpl`;
      lines.push(
        `if [ -f ${src} ]; then`,
        `  envsubst < ${src} > ${dst}`,
        `  chown bun:bun ${dst}`,
        `  chmod ${tf.mode ?? '0644'} ${dst}`,
        'fi',
        '',
      );
    }
  }

  lines.push(
    chownLine,
    '',
    'exec gosu bun "$@"',
    '',
  );

  return lines.join('\n');
}
