/**
 * Entrypoint shell script generator.
 *
 * Docker bind mounts that don't exist on the host get auto-created by
 * docker-compose at `up` time — but as root-owned directories.  Our agents
 * run as the `bun` user (UID 1000) inside the container, so they can't
 * write to those root-owned dirs and crash on first state-write.
 *
 * Solution: ENTRYPOINT runs as root, chowns every RW bind-mount target,
 * then exec-drops to `bun` via gosu.  The container's CMD becomes the
 * `bun src/index.ts ...` invocation, executed under bun's UID.
 *
 * The list of paths to chown comes from compose.ts's `chownTargets`
 * helper so the two generators stay in lockstep — anything compose
 * mounts RW gets chown'd here.
 */

import type { GeneratorInput } from '../types.js';
import { chownTargets } from './compose.js';

export function generateEntrypoint(input: GeneratorInput): string {
  const targets = chownTargets(input.walks);
  const chownLine = targets.length > 0
    ? `chown -R bun:bun ${targets.join(' ')}`
    : '# no RW bind-mount targets to chown';

  return [
    '#!/bin/sh',
    '#',
    '# Auto-generated by connectome-cook.  Runs as root at container start,',
    '# fixes ownership of bind-mounted dirs (which docker-compose creates as',
    '# root if the host paths did not exist), then exec-drops to the `bun`',
    '# user via gosu and runs the CMD (`bun src/index.ts <recipe>` by default).',
    '#',
    '# This is the standard Postgres/Redis-style "container init as root,',
    '# real work as service user" pattern — needed because RW bind mounts',
    '# punch through the in-image chown.',
    '#',
    'set -e',
    '',
    chownLine,
    '',
    'exec gosu bun "$@"',
    '',
  ].join('\n');
}
