/**
 * README generator — Phase 2 of BUILD-PLAN.md.
 *
 * Templates an operator-facing README that lives next to the generated
 * Dockerfile + docker-compose.yml. The audience is "someone who just got
 * the cook output dir and now needs to make it run on their box": tells
 * them what the image bundles, what they need to bring (env vars, .zuliprc),
 * how to build/attach/detach, where persistent state lives, and the small
 * set of trip-wires they'll otherwise hit.
 *
 * Reference for visual review (NOT a diff target):
 *   examples/triumvirate/README.md — hand-tuned for the Triumvirate. Cook's
 *   README must be data-driven enough to make sense for any recipe; the
 *   shape and section ordering match the example, the prose is generic.
 *
 * Pure string templating with template literals — no markdown library, no
 * helper engine. Operators paste this into editors (VS Code, neovim) and
 * read it via GitHub renderers; we stick to plain CommonMark.
 *
 * Sections (in order):
 *   1. Title + 1-paragraph description (from walks[0].recipe.description).
 *   2. What's in the image — the cloned ref of connectome-host, language
 *      runtimes, MCP sources, baked-in recipes.
 *   3. Prerequisites — Docker, Anthropic key, plus per-source items we can
 *      introspect (Zulip, GitLab) — fall back to generic "set vars in .env".
 *   4. Quick start — 4 numbered shell steps (cp .env.example, fill prereq
 *      files, build, attach).
 *   5. Detach without stopping — Ctrl+P/Ctrl+Q dance + the /quit trap.
 *   6. Persistence — table of every workspace mount → host bind path.
 *   7. Troubleshooting — small canned set of "you'll hit this" items.
 *   8. What this image is NOT — short caveats.
 *   9. Footer — generator version + how to regenerate.
 */

import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import type {
  GeneratorInput,
  McpSource,
  WalkResult,
} from '../types.js';
import type {
  Recipe,
  RecipeMcpServer,
  RecipeWorkspaceMount,
} from '../vendor/recipe.js';
import { slugify } from '../slug.js';

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Generate the operator-facing README for the cook output directory.
 *
 * Throws if `input.walks` is empty (caller error — there must be at least
 * the parent recipe).
 */
export function generateReadme(input: GeneratorInput): string {
  if (input.walks.length === 0) {
    throw new Error('generateReadme: walks must contain at least the parent recipe');
  }

  const parent = input.walks[0]!;
  const parentName = parent.recipe.name;
  const description =
    parent.recipe.description ?? 'Auto-generated by connectome-cook.';
  const serviceName = slugify(parentName);
  const cookVersion = readCookVersion();

  // Capability flags discovered by inspecting the recipe tree.
  const usesZulip = anyRecipeUsesZulip(input.walks);
  const usesGitLab = anyRecipeUsesGitLab(input.walks);
  const hasPipEditableSource = input.sources.some(
    (s) => s.install.kind === 'pip-editable'
      || (s.install.kind === 'custom' && s.install.runtime === 'python3'),
  );
  const mounts = collectWorkspaceMounts(input.walks);

  const sections: string[] = [
    renderTitle(parentName, description),
    renderWhatsInTheImage(input, hasPipEditableSource),
    renderPrerequisites(usesZulip, usesGitLab),
    renderQuickStart(serviceName, usesZulip, parentName),
    renderDetach(),
    renderPersistence(mounts),
    renderTroubleshooting(),
    renderWhatThisImageIsNot(),
    renderFooter(cookVersion, parentName),
  ];

  // Single trailing newline; sections already end with one.
  return sections.join('\n') + '\n';
}

// ---------------------------------------------------------------------------
// Section renderers
// ---------------------------------------------------------------------------

function renderTitle(parentName: string, description: string): string {
  return [
    `# ${parentName} — Dockerized`,
    '',
    description,
    '',
  ].join('\n');
}

function renderWhatsInTheImage(
  input: GeneratorInput,
  hasPython: boolean,
): string {
  const lines: string[] = [`## What's in the image`, ''];

  // connectome-host. We don't know the exact ref baked in (it's a build arg
  // set by the dockerfile generator with default `main`). Mention that the
  // generated Dockerfile pins it via a build-arg; operators that override
  // know what they did.
  lines.push(
    '- **connectome-host** — cloned at build time (see `CH_REF` build-arg in the Dockerfile; defaults to `main`).',
  );

  // Runtimes. Bun and Node are always present (bun for the host, node for
  // any npx-style MCP server commands). Python only if a source needs it.
  lines.push('- **Bun** 1.x — runtime for connectome-host and the agent processes.');
  lines.push('- **Node 20** — runtime for `npx`/`node`-launched MCP servers.');
  if (hasPython) {
    lines.push('- **python3** — for Python-based MCP servers (one or more sources install via pip-editable).');
  }
  lines.push('- **tini** as PID 1 — signal forwarding + zombie reaping.');

  // MCP sources baked in.
  if (input.sources.length > 0) {
    for (const source of input.sources) {
      lines.push(`- ${describeSource(source)}`);
    }
  }

  // Recipes baked in.
  if (input.walks.length > 0) {
    const recipeNames = input.walks
      .map((w) => `\`${w.recipe.name}\``)
      .join(', ');
    lines.push(`- **Baked-in recipes:** ${recipeNames}.`);
  }

  lines.push('');
  return lines.join('\n');
}

function renderPrerequisites(
  usesZulip: boolean,
  usesGitLab: boolean,
): string {
  const lines: string[] = [
    '## Prerequisites',
    '',
    '- **Docker Engine 23+** with Compose v2 (`docker compose ...`, not `docker-compose ...`) and BuildKit (default in 23+).',
    '- **An Anthropic API key** ([console.anthropic.com](https://console.anthropic.com/)). Set it as `ANTHROPIC_API_KEY` in `.env`.',
  ];

  if (usesZulip) {
    lines.push(
      '- **A Zulip account + bot** with credentials in a `.zuliprc` file. Place it next to `docker-compose.yml` before the first `up`. The Zulip MCP reads the path from `ZULIP_RC_PATH` (defaults to `./.zuliprc`).',
    );
  }

  if (usesGitLab) {
    lines.push(
      '- **A GitLab Personal Access Token** with `read_api` and `read_repository` scopes (add `api` if any agent writes back). Set as `GITLAB_TOKEN` in `.env`; set the API URL via `GITLAB_API_URL` if you use a self-hosted GitLab.',
    );
  }

  lines.push(
    '- **All other recipe-referenced env vars** — see `.env.example` for the full list. Cook scans the recipe tree for `${VAR}` placeholders and writes a template; fill it in before `up`.',
  );
  lines.push('');
  return lines.join('\n');
}

function renderQuickStart(
  serviceName: string,
  usesZulip: boolean,
  parentName: string,
): string {
  const lines: string[] = [
    '## Quick start',
    '',
    `From this directory:`,
    '',
    '```bash',
    '# 1. Create your env file from the template and edit it.',
    'cp .env.example .env',
    '$EDITOR .env',
    '',
  ];

  if (usesZulip) {
    lines.push('# 2. Drop your Zulip bot credentials here.');
    lines.push('cp ~/Downloads/zuliprc .zuliprc');
    lines.push('chmod 600 .zuliprc');
    lines.push('');
    lines.push('# 3. Build the image and start the container in the background.');
    lines.push('docker compose up -d --build');
    lines.push('');
    lines.push(`# 4. Attach to the conductor TUI.`);
    lines.push(`docker attach ${serviceName}`);
  } else {
    lines.push('# 2. Build the image and start the container in the background.');
    lines.push('docker compose up -d --build');
    lines.push('');
    lines.push(`# 3. Attach to the conductor TUI.`);
    lines.push(`docker attach ${serviceName}`);
  }

  lines.push('```');
  lines.push('');
  lines.push(
    `The service name (\`${serviceName}\`) is derived from the parent recipe name (\`${parentName}\`) by lowercasing, replacing each run of non-alphanumeric characters with a single \`-\`, and trimming leading/trailing hyphens.`,
  );
  lines.push('');
  lines.push(
    'First build is slow (clones connectome-host + each MCP source, runs `bun install` and the per-source build). Subsequent builds reuse the layer cache and are much faster.',
  );
  lines.push('');
  return lines.join('\n');
}

function renderDetach(): string {
  return [
    '## Detach without stopping',
    '',
    'The most important Docker-specific gotcha:',
    '',
    '> **Use `Ctrl+P Ctrl+Q` to detach, NOT `/quit` inside the conductor.**',
    '',
    'When the conductor TUI is PID 1 in the container (which it is here), `/quit` exits the conductor → PID 1 dies → the container shuts down → every fleet child dies with it. The "detach + leave running" semantics from the non-Docker setup do not apply.',
    '',
    'Use Docker\'s built-in detach sequence instead: press **Ctrl+P then Ctrl+Q** while attached. The TUI disconnects but the conductor (and any fleet children) keep running. Re-attach later with the same `docker attach <service>` command.',
    '',
    'To stop everything cleanly: `docker compose down`. This sends SIGTERM to the container; tini forwards it to the conductor, which runs its graceful-shutdown logic before the compose `stop_grace_period` (30s) elapses.',
    '',
  ].join('\n');
}

function renderPersistence(mounts: PersistenceEntry[]): string {
  const lines: string[] = [
    '## Persistence',
    '',
    'All persistent state is bind-mounted into this directory. You can inspect, back up, or edit any of these from the host with normal tools:',
    '',
  ];

  if (mounts.length === 0) {
    lines.push(
      '_(This recipe does not declare any workspace mounts; only the container\'s internal filesystem is used.)_',
    );
    lines.push('');
    return lines.join('\n');
  }

  lines.push('| Host path (relative to this dir) | Container path | Mode | Source |');
  lines.push('|---|---|---|---|');
  for (const m of mounts) {
    lines.push(`| \`${m.host}\` | \`${m.container}\` | ${m.mode} | ${m.source} |`);
  }
  lines.push('');
  lines.push(
    'These directories are created on the host on first `up` if they don\'t exist. Container UID is `1000` (the `bun` user); on Linux/WSL2 default accounts (also UID 1000) this Just Works. If you hit permission errors, `chown -R 1000:1000` the offending directories on the host.',
  );
  lines.push('');
  return lines.join('\n');
}

function renderTroubleshooting(): string {
  return [
    '## Troubleshooting',
    '',
    '- **First build is slow.** Expected — the build clones connectome-host and every MCP source, then runs `bun install` plus each source\'s install (`npm install && npm run build` for npm, `pip install -e .` for pip-editable, etc.). Re-builds reuse the layer cache.',
    '- **Can\'t see the TUI on `docker attach`.** Make sure the compose file has `stdin_open: true` and `tty: true` (cook sets both). Try pressing a key, resizing the terminal, or detach (`Ctrl+P Ctrl+Q`) and re-attach.',
    '- **An MCP server failed at startup.** Run `docker compose logs <service>` to see the conductor\'s view. As of `@animalabs/agent-framework@0.3.0`, a single MCP server failure is fatal for the agent that uses it — fix the underlying issue (usually a missing or malformed credential) and restart with `docker compose up -d --force-recreate`.',
    '- **Build fails with "secret not found" / `--mount=type=secret`.** Some MCP sources need a build-time secret to clone a private repo. Cook writes each secret as a 0600-mode file at `<outDir>/<NAME>` (one per `source.authSecret`), and the generated `docker-compose.yml` references them via the top-level `secrets:` block — `docker compose build` reads the files automatically. If a file is missing or empty, populate it manually (`echo "<token>" > <NAME> && chmod 600 <NAME>`) before re-running the build. BuildKit must be enabled (default in Docker 23+).',
    '- **API error 401 from Zulip / GitLab on first run.** Credential file or env var is wrong. For Zulip, verify the file made it into the container: `docker compose exec <service> cat /app/.zuliprc`. For GitLab, double-check the token scopes and that `GITLAB_API_URL` matches your instance.',
    '- **Container exits immediately.** Almost always missing `ANTHROPIC_API_KEY`. `docker compose config` will show whether `.env` is being loaded; the container logs will name the missing variable.',
    '',
  ].join('\n');
}

function renderWhatThisImageIsNot(): string {
  return [
    '## What this image is *not*',
    '',
    '- **Not multi-arch.** Built for the host architecture only. For amd64+arm64 images, use `docker buildx` directly.',
    '- **Not pushed to a registry.** The image stays local. `docker push <image-name>:latest` if you want to share it.',
    '- **Not validating credentials at build time.** Tokens, API keys, and Zulip rc files are checked at first runtime use — a misconfigured secret will fail at `docker compose up`, not during `docker compose build`.',
    '',
  ].join('\n');
}

function renderFooter(cookVersion: string, parentName: string): string {
  return [
    '---',
    '',
    `_Generated by connectome-cook v${cookVersion}. To regenerate: \`cook build ${parentName}\`._`,
    '',
  ].join('\n');
}

// ---------------------------------------------------------------------------
// Source description helpers
// ---------------------------------------------------------------------------

/**
 * Render one bullet describing how an `McpSource` ends up in the image.
 *
 * Sibling-copy: "(sibling-copy)" is enough — operator knows they're
 * supplying the source themselves at build time.
 *
 * Sourced: include the URL + ref (defaulting to "main" if unset, since
 * source-detector normalizes to "main") and the in-container path.
 */
function describeSource(source: McpSource): string {
  if (source.install.kind === 'sibling-copy') {
    return `**${source.install.siblingDir}** (sibling-copy from build context) → \`${source.inContainerPath}\``;
  }

  const refSuffix = source.ref && source.ref !== 'main' ? `@${source.ref}` : '';
  return `**${source.url}**${refSuffix} → \`${source.inContainerPath}\``;
}

// ---------------------------------------------------------------------------
// Capability detection
// ---------------------------------------------------------------------------

/**
 * Heuristic: any mcpServer references `.zuliprc` (in args/command/env values)
 * OR has an env entry named `ZULIP_RC_PATH` OR has a source URL that
 * mentions "zulip". Catches the example shape (`env.ZULIP_RC_PATH`) and the
 * git-clone case (`source.url = ".../zulip_mcp.git"`).
 *
 * Same shape as compose.ts's anyRecipeUsesZulip but with the source-URL
 * check folded in so we light up the prereq line for builds that bake in a
 * Zulip MCP without the .zuliprc-mounting heuristic firing yet.
 */
function anyRecipeUsesZulip(walks: WalkResult[]): boolean {
  for (const walk of walks) {
    const servers = walk.recipe.mcpServers;
    if (!servers) continue;
    for (const server of Object.values(servers)) {
      if (mcpServerReferencesZulip(server)) return true;
    }
  }
  return false;
}

function mcpServerReferencesZulip(server: RecipeMcpServer): boolean {
  if (server.env) {
    if ('ZULIP_RC_PATH' in server.env) return true;
    for (const v of Object.values(server.env)) {
      if (typeof v === 'string' && v.includes('.zuliprc')) return true;
    }
  }
  if (server.command && server.command.includes('.zuliprc')) return true;
  if (server.args) {
    for (const arg of server.args) {
      if (arg.includes('.zuliprc')) return true;
    }
  }
  if (server.source?.url && server.source.url.toLowerCase().includes('zulip')) {
    return true;
  }
  return false;
}

/**
 * Heuristic for GitLab: any mcpServer with a key that matches "gitlab",
 * an args entry mentioning gitlab, an env entry named like a GitLab token,
 * or a source URL mentioning gitlab.
 */
function anyRecipeUsesGitLab(walks: WalkResult[]): boolean {
  for (const walk of walks) {
    const servers = walk.recipe.mcpServers;
    if (!servers) continue;
    for (const [name, server] of Object.entries(servers)) {
      if (name.toLowerCase().includes('gitlab')) return true;
      if (mcpServerReferencesGitLab(server)) return true;
    }
  }
  return false;
}

function mcpServerReferencesGitLab(server: RecipeMcpServer): boolean {
  if (server.env) {
    for (const k of Object.keys(server.env)) {
      if (k.toUpperCase().includes('GITLAB')) return true;
    }
  }
  if (server.args) {
    for (const arg of server.args) {
      if (arg.toLowerCase().includes('gitlab')) return true;
    }
  }
  if (server.source?.url && server.source.url.toLowerCase().includes('gitlab')) {
    return true;
  }
  return false;
}

// ---------------------------------------------------------------------------
// Workspace mount aggregation
// ---------------------------------------------------------------------------

interface PersistenceEntry {
  /** Host bind path, including leading `./`. */
  host: string;
  /** Container bind path. Mirrors compose.ts's `/app/<lastSegment>` shape. */
  container: string;
  /** Display string: `read-only` or `read-write`. */
  mode: string;
  /** Which recipe(s) declare this mount, for the right-most table column. */
  source: string;
}

/**
 * Collect every workspace mount from every walked recipe, deduplicated by
 * container path (matches compose.ts first-write-wins). The `source` column
 * lists every recipe that declared a mount with the same container path so
 * operators can trace a directory back to the agent that uses it.
 */
function collectWorkspaceMounts(walks: WalkResult[]): PersistenceEntry[] {
  const byContainer = new Map<string, PersistenceEntry>();

  for (const walk of walks) {
    const workspace = walk.recipe.modules?.workspace;
    if (!workspace || typeof workspace !== 'object' || !workspace.mounts) continue;

    const recipeLabel = walk.recipe.name;
    for (const mount of workspace.mounts) {
      const entry = mountToEntry(mount, recipeLabel);
      const existing = byContainer.get(entry.container);
      if (!existing) {
        byContainer.set(entry.container, entry);
        continue;
      }
      // Append recipe to the source column if it isn't already listed.
      const sources = existing.source.split(', ');
      if (!sources.includes(recipeLabel)) {
        existing.source = `${existing.source}, ${recipeLabel}`;
      }
    }
  }

  return Array.from(byContainer.values());
}

function mountToEntry(
  mount: RecipeWorkspaceMount,
  recipeLabel: string,
): PersistenceEntry {
  const stripped = mount.path.replace(/^\.\//, '').replace(/^\/+/, '');
  const lastSegment = stripped.split('/').filter(Boolean).pop() ?? slugify(mount.name);
  return {
    host: `./${stripped}`,
    container: `/app/${lastSegment}`,
    mode: mount.mode === 'read-only' ? 'read-only' : 'read-write',
    source: recipeLabel,
  };
}

// ---------------------------------------------------------------------------
// Cook version lookup
// ---------------------------------------------------------------------------

/**
 * Read the cook package version from package.json. Returns "0.0.0" if the
 * lookup fails (best-effort — we never want README generation to throw on
 * a metadata read).
 */
function readCookVersion(): string {
  try {
    const here = dirname(fileURLToPath(import.meta.url));
    // src/generators/readme.ts → ../../package.json
    const pkgPath = resolve(here, '..', '..', 'package.json');
    const raw = readFileSync(pkgPath, 'utf-8');
    const pkg = JSON.parse(raw) as { version?: unknown };
    if (typeof pkg.version === 'string' && pkg.version) return pkg.version;
  } catch {
    // ignore — fall through to the placeholder.
  }
  return '0.0.0';
}
