/**
 * Tests for the README generator. Uses bun:test.
 *
 * Coverage:
 *   1. Triumvirate fixture (the example recipe tree) — asserts the title,
 *      Anthropic key prereq, Zulip prereq, the single zulip_mcp source
 *      bullet, and the `docker attach <slug>` line.
 *   2. Synthetic recipe with no MCP servers and one workspace mount —
 *      asserts no false MCP/Zulip/GitLab mentions, but Quick start +
 *      Persistence + Troubleshooting are still present.
 */

import { describe, expect, test } from 'bun:test';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { generateReadme } from './readme.js';
import { walkRecipe } from '../walker.js';
import { detectSources } from '../source-detector.js';
import { collectEnvVars } from '../env-collector.js';
import type { GeneratorInput, WalkResult } from '../types.js';
import type { Recipe } from '../vendor/recipe.js';

const HERE = dirname(fileURLToPath(import.meta.url));
const TRIUMVIRATE_PARENT = resolve(
  HERE,
  '..',
  '..',
  'examples',
  'triumvirate',
  'recipes',
  'triumvirate.json',
);

function defaultBuildOptions(): GeneratorInput['options'] {
  return {
    outDir: '/tmp/cook-test',
    noPrompts: true,
    strict: false,
    pinRefs: false,
  };
}

describe('generateReadme — triumvirate fixture', () => {
  test('renders all required sections with example data', async () => {
    const walks = await walkRecipe(TRIUMVIRATE_PARENT);
    const sources = detectSources(walks, { strict: false });
    const envVars = collectEnvVars(walks);

    const input: GeneratorInput = {
      walks,
      sources,
      envVars,
      options: defaultBuildOptions(),
    };

    const out = generateReadme(input);

    // Title with parent recipe name.
    expect(out.startsWith('# Knowledge Mining Triumvirate — Dockerized')).toBe(true);

    // Description from the parent recipe.
    expect(out).toContain(
      'Conductor that supervises miner + reviewer + clerk child processes',
    );

    // What's in the image — connectome-host + tini + bun + node baseline.
    expect(out).toContain('connectome-host');
    expect(out).toContain('tini');
    expect(out).toContain('Bun');
    expect(out).toContain('Node 20');

    // The one Zulip MCP source bullet, with its inContainerPath.
    expect(out).toContain('zulip_mcp');
    expect(out).toContain('/zulip_mcp');

    // Baked-in recipes line — every walked recipe by name.
    expect(out).toContain('Knowledge Mining Triumvirate');
    expect(out).toContain('Knowledge Miner (generic Triumvirate example)');
    expect(out).toContain('Knowledge Reviewer');
    expect(out).toContain('Library Frontdesk');

    // Prerequisites.
    expect(out).toContain('Anthropic API key');
    expect(out).toContain('ANTHROPIC_API_KEY');
    expect(out).toContain('Zulip');
    expect(out).toContain('.zuliprc');
    expect(out).toContain('GitLab');

    // Quick start with the slugified service name.
    expect(out).toContain('cp .env.example .env');
    expect(out).toContain('docker compose up -d --build');
    expect(out).toContain('docker attach knowledge-mining-triumvirate');

    // Detach instruction.
    expect(out).toContain('Ctrl+P');
    expect(out).toContain('Ctrl+Q');
    expect(out).toContain('/quit');

    // Persistence — should list at least one mount from the children.
    expect(out).toContain('## Persistence');
    expect(out).toContain('| Host path');
    // Several known triumvirate workspace mounts collapse onto these
    // container paths in compose.ts; assert one to confirm rendering.
    expect(out).toContain('/app/output');

    // Troubleshooting + What this image is NOT + Footer.
    expect(out).toContain('## Troubleshooting');
    expect(out).toContain("## What this image is *not*");
    expect(out).toContain('Not multi-arch');
    expect(out).toContain('Not pushed to a registry');
    expect(out).toContain('Generated by connectome-cook');
    expect(out).toContain('cook build Knowledge Mining Triumvirate');
  });

  test('output ends with a trailing newline', async () => {
    const walks = await walkRecipe(TRIUMVIRATE_PARENT);
    const sources = detectSources(walks, { strict: false });
    const envVars = collectEnvVars(walks);

    const out = generateReadme({
      walks,
      sources,
      envVars,
      options: defaultBuildOptions(),
    });

    expect(out.endsWith('\n')).toBe(true);
  });
});

describe('generateReadme — synthetic recipe with no MCP servers', () => {
  test('does not mention MCP/Zulip/GitLab when nothing references them, but still has the standard scaffolding', () => {
    const recipe: Recipe = {
      name: 'Lonely Solo Agent',
      description: 'A single agent with one workspace mount and no MCP servers.',
      version: '0.1.0',
      agent: { systemPrompt: 'You are a lonely agent.' },
      modules: {
        workspace: {
          mounts: [
            { name: 'notes', path: './notes', mode: 'read-write' },
          ],
        },
      },
    };
    const walks: WalkResult[] = [
      { path: '/recipes/solo.json', recipe },
    ];
    const input: GeneratorInput = {
      walks,
      sources: [],
      envVars: [],
      options: defaultBuildOptions(),
    };

    const out = generateReadme(input);

    // Title + description from the synthetic recipe.
    expect(out.startsWith('# Lonely Solo Agent — Dockerized')).toBe(true);
    expect(out).toContain('A single agent with one workspace mount');

    // Quick start is always present and uses the slugified service name.
    expect(out).toContain('## Quick start');
    expect(out).toContain('docker attach lonely-solo-agent');
    expect(out).toContain('cp .env.example .env');

    // Persistence is present and lists the one workspace mount.
    expect(out).toContain('## Persistence');
    expect(out).toContain('./notes');
    expect(out).toContain('/app/notes');

    // Troubleshooting is always present.
    expect(out).toContain('## Troubleshooting');

    // No false MCP server mentions: there should be no per-source bullet
    // (sources is empty) and no Zulip/GitLab/.zuliprc prereqs.
    expect(out).not.toContain('A Zulip account');
    expect(out).not.toContain('A GitLab Personal Access Token');
    expect(out).not.toContain('cp ~/Downloads/zuliprc');
    expect(out).not.toContain('chmod 600 .zuliprc');

    // Footer with regenerate command.
    expect(out).toContain('Generated by connectome-cook');
  });

  test('omits the persistence table when the recipe has no workspace mounts', () => {
    const recipe: Recipe = {
      name: 'No-Mounts Agent',
      agent: { systemPrompt: 'no mounts' },
    };
    const walks: WalkResult[] = [
      { path: '/recipes/no-mounts.json', recipe },
    ];

    const out = generateReadme({
      walks,
      sources: [],
      envVars: [],
      options: defaultBuildOptions(),
    });

    expect(out).toContain('## Persistence');
    // Falls back to the explanatory line when there are no mounts.
    expect(out).toContain('does not declare any workspace mounts');
    // No table headers in this branch.
    expect(out).not.toContain('| Host path');
  });

  test('uses the auto-generated description fallback when the recipe lacks one', () => {
    const recipe: Recipe = {
      name: 'Anonymous Agent',
      agent: { systemPrompt: 'hi' },
    };
    const out = generateReadme({
      walks: [{ path: '/x.json', recipe }],
      sources: [],
      envVars: [],
      options: defaultBuildOptions(),
    });
    expect(out).toContain('Auto-generated by connectome-cook.');
  });
});
