/**
 * `cook init` — scaffold a starter recipe.
 *
 * Templates are inline (not file-based) so cook stays a single binary
 * with no template dir to ship.  Add new templates by extending the
 * `TEMPLATES` map below.
 */

import { existsSync, writeFileSync } from 'node:fs';
import type { Recipe } from './vendor/recipe.js';

export type TemplateName = 'minimal' | 'zulip-agent' | 'triumvirate';

interface Template {
  description: string;
  build(name: string): Recipe;
  /** Companion files written to disk alongside the recipe.  Empty for
   *  most templates; the triumvirate template writes child recipes too. */
  companions?: (name: string) => Array<{ filename: string; content: string }>;
}

const TEMPLATES: Record<TemplateName, Template> = {
  minimal: {
    description: 'Single agent, no MCP servers, generic system prompt.',
    build: (name) => ({
      name,
      description: 'Generated by `cook init` — minimal starter recipe.',
      version: '0.1.0',
      agent: {
        name: name.toLowerCase().replace(/\s+/g, '-'),
        model: 'claude-opus-4-7',
        systemPrompt:
          'You are a helpful assistant.\n\nThis is a starter recipe — replace this prompt with the role you want the agent to play.',
      },
      modules: {
        subagents: true,
        lessons: true,
        retrieval: true,
        wake: true,
        workspace: true,
      },
    }),
  },

  'zulip-agent': {
    description: 'Single agent staffing a Zulip channel via the antra-tess/zulip_mcp adapter.',
    build: (name) => ({
      name,
      description: 'Generated by `cook init` — single agent on Zulip.',
      version: '0.1.0',
      agent: {
        name: name.toLowerCase().replace(/\s+/g, '-'),
        model: 'claude-opus-4-7',
        maxTokens: 16384,
        systemPrompt:
          'You are an agent that staffs a Zulip channel.\n\nWake on every channel message; read the channel context; reply with relevant, sourced answers.\n\nReplace this prompt with the role and channel-specific guidance you want the agent to play.',
        strategy: {
          type: 'frontdesk',
          headWindowTokens: 4000,
          recentWindowTokens: 30000,
        },
      },
      mcpServers: {
        zulip: {
          command: 'node',
          args: ['../zulip_mcp/build/index.js'],
          env: {
            ENABLE_ZULIP: 'true',
            ENABLE_DISCORD: 'false',
            ZULIP_RC_PATH: './.zuliprc',
            ZULIP_SUBSCRIBE: '<channel-name>',
          },
          source: {
            url: 'https://github.com/antra-tess/zulip_mcp.git',
            install: 'npm',
          },
        },
      },
      modules: {
        subagents: true,
        lessons: true,
        retrieval: true,
        wake: true,
        workspace: true,
      },
    }),
  },

  triumvirate: {
    description: 'Three-agent fleet (miner + reviewer + clerk) with conductor — the canonical knowledge-mining setup.',
    build: (name) => ({
      name,
      description: 'Generated by `cook init` — Knowledge Mining Triumvirate (conductor + miner + reviewer + clerk).',
      version: '0.1.0',
      agent: {
        name: 'conductor',
        model: 'claude-opus-4-7',
        maxTokens: 8192,
        systemPrompt:
          'You are the Conductor of the Knowledge Mining Triumvirate.\n\nThree child agents (miner, reviewer, clerk) run as cross-process children under your supervision.  Stay quiet unless the user asks something or a child crashes.  Replace this prompt to add team-specific guidance.',
      },
      modules: {
        fleet: {
          children: [
            { name: 'miner', recipe: './miner.json', autoStart: true, subscription: ['lifecycle', 'inference:speech'] },
            { name: 'reviewer', recipe: './reviewer.json', autoStart: true, subscription: ['lifecycle', 'inference:speech'] },
            { name: 'clerk', recipe: './clerk.json', autoStart: true, subscription: ['lifecycle', 'inference:speech'] },
          ],
        },
      },
    }),
    companions: (name) => [
      {
        filename: 'miner.json',
        content: JSON.stringify(
          {
            name: `${name} — Miner`,
            agent: { name: 'miner', model: 'claude-opus-4-7', systemPrompt: 'You extract knowledge from sources.  Replace this prompt with team-specific guidance.' },
            modules: { subagents: true, lessons: true, retrieval: true, workspace: true },
          },
          null,
          2,
        ) + '\n',
      },
      {
        filename: 'reviewer.json',
        content: JSON.stringify(
          {
            name: `${name} — Reviewer`,
            agent: { name: 'reviewer', model: 'claude-opus-4-7', systemPrompt: 'You critique mined documents.  Replace this prompt with team-specific guidance.' },
            modules: { subagents: true, lessons: true, retrieval: true, workspace: true },
          },
          null,
          2,
        ) + '\n',
      },
      {
        filename: 'clerk.json',
        content: JSON.stringify(
          {
            name: `${name} — Clerk`,
            agent: { name: 'clerk', model: 'claude-opus-4-7', systemPrompt: 'You staff a question channel and answer from the library.  Replace this prompt with team-specific guidance.' },
            modules: { subagents: true, lessons: true, retrieval: true, workspace: true },
          },
          null,
          2,
        ) + '\n',
      },
    ],
  },
};

export function listTemplates(): Array<{ name: TemplateName; description: string }> {
  return (Object.entries(TEMPLATES) as Array<[TemplateName, Template]>).map(([name, t]) => ({
    name,
    description: t.description,
  }));
}

/** Scaffold a starter recipe (and companion files for multi-agent templates).
 *  Throws if any target path already exists. */
export function scaffoldRecipe(
  name: string,
  template: TemplateName,
  outPath: string,
): { written: string[] } {
  const tpl = TEMPLATES[template];
  if (!tpl) throw new Error(`unknown template: ${template}`);
  if (existsSync(outPath)) {
    throw new Error(`refusing to overwrite existing file: ${outPath}`);
  }
  const recipe = tpl.build(name);
  writeFileSync(outPath, JSON.stringify(recipe, null, 2) + '\n');
  const written = [outPath];

  for (const comp of tpl.companions?.(name) ?? []) {
    const compPath = outPath.replace(/[^/]+$/, comp.filename);
    if (existsSync(compPath)) {
      throw new Error(`refusing to overwrite existing companion: ${compPath}`);
    }
    writeFileSync(compPath, comp.content);
    written.push(compPath);
  }
  return { written };
}
